### ISSUE TITLE
must use the new Firebase Authentication SDKs available

### ISSUE THREAD

**Issue by Harris-Aaron** [xifengzhu/ionic-firebase-chat#1]
hello xifengzhu!  en,I have a problem...   
1. Replace the firebase url

2.ionic serve

3.Create New Account

alert the error:
Error: Error: Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/

i go to the page [http://firebase.google.com/docs/auth/] and [https://console.developers.google.com] 

Create credentials > Service account key. Select New service account, type any name, select JSON as the key type, and click Create

got a myProject-a38c11530305.json

But this document does not seem to be related to the project

**Comment by marw3n** [comment]
same problem here :/
looks like this project is using an old Firebase SDK version and we are using it to set up a connection to a new Firebase environment
the firebase console create just new firebase SDK's projects (firebase#3)
any solution ?

**Comment by baddot** [comment]
im having the sample problem it uses the legacy firebase console. where when i created from the console.firebase is the new legacy it shows the same error

Error: Error: Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/

**Comment by 32xnabin** [comment]
same problem

**Comment by xifengzhu** [comment]
Really appreciate the feedback!  who can tell me how to reproduce the problem.

**Comment by 32xnabin** [comment]
@xifengzhu I simply replaced the firebase url with my own url and try to do ionic serve and this issue appears. don't use old firebase account create new firebase project or if possible create new gmail id. Thanks in advance

**Comment by xifengzhu** [comment]
I migrating the AngularFire from 1.x.x to 2.x.x with the document https://github.com/firebase/angularfire/blob/master/docs/migration/1XX-to-2XX.md.  The problem is gone.
